name: Deploy MERGE-BOT with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MERGE-BOT repository
        run: |
          git clone https://${{ secrets.TOKEN }}github.com/appujohn007/MERGE-BOT.git
          cd MERGE-BOT

      - name: Install Essentials
        run: |
          sudo apt-get -y update && \
          sudo apt-get -y upgrade && \
          sudo apt-get install --no-install-recommends -y git wget curl pv jq ffmpeg neofetch mediainfo && \
          sudo apt-get clean

      - name: Install Pip Dependencies
        run: |
          pip install -r needs.txt

      - name: Run bot
        run: |
          python bot.py
